<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <BuildDir>$(SolutionDir)/Thunderstore/</BuildDir>
    <TSPackageDir>$(BuildDir)/package/</TSPackageDir>
    <TSPackagePluginDir>$(TSPackageDir)/plugins/$(SolutionName)/</TSPackagePluginDir>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="libs\**" />
    <EmbeddedResource Remove="libs\**" />
    <None Remove="libs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="RiskOfRain2.GameLibs" Version="1.4.1-r.0" GeneratePathProperty="true"/>
    <PackageReference Include="MMHOOK.RoR2" Version="2025.12.9" NoWarn="NU1701" />
    <PackageReference Include="RoR2BepInExPack" Version="1.41.0" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.33" GeneratePathProperty="true" />
    <PackageReference Include="R2API.Core" Version="5.3.0" />
    <PackageReference Include="R2API.ContentManagement" Version="1.0.10" />
    <PackageReference Include="R2API.Prefab" Version="1.1.1" />
    <PackageReference Include="R2API.Language" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
      <Reference Include="RiskOfOptions">
      <HintPath>libs\RiskOfOptions.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="BuildTSPackage" AfterTargets="Build">
    <MakeDir Directories="$(TSPackageDir);$(TSPackagePluginDir)" />
    <Copy SourceFiles="$(SolutionDir)manifest.json;$(SolutionDir)README.md;$(SolutionDir)CHANGELOG.md" DestinationFolder="$(TSPackageDir)" />

    <Copy SourceFiles="$(BuildDir)icon.png" DestinationFolder="$(TSPackageDir)" ContinueOnError="true" />

    <ItemGroup>
      <LangFiles Include="$(SolutionDir)lang/**/*.*" />
    </ItemGroup>

    <Copy SourceFiles="@(LangFiles)" DestinationFolder="$(TSPackagePluginDir)/lang/%(RecursiveDir)" />

    <Delete Files="$(TSPackagePluginDir)/$(AssemblyName).dll" />
    <Delete Files="$(TSPackagePluginDir)/$(AssemblyName).pdb" Condition="'$(Configuration)'=='Release'" ContinueOnError="true" />

    <Copy SourceFiles="$(OutDir)$(AssemblyName).dll" DestinationFolder="$(TSPackagePluginDir)" />
    <Copy SourceFiles="$(OutDir)$(AssemblyName).pdb" DestinationFolder="$(TSPackagePluginDir)" Condition="'$(Configuration)'=='Debug'" ContinueOnError="true" />

    <ZipDirectory SourceDirectory="$(TSPackageDir)" DestinationFile="$(BuildDir)/$(SolutionName).zip" Overwrite="true" />
  </Target>

</Project>
